# Generated by Django 5.2.5 on 2025-10-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=30)),
                ('movie_location', models.CharField(max_length=30)),
                ('movie_timings', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reservation_locations', models.CharField(max_length=30)),
                ('reservation_time', models.TimeField()),
                ('number_of_seats', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.movies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
