# Generated by Django 5.2.5 on 2025-10-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_movies_users_reservations_delete_course_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_timings',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_time',
        ),
    ]
