# Generated by Django 5.2.5 on 2025-10-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_movies_movie_timings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_password',
        ),
    ]
