# Generated by Django 5.2.5 on 2025-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_users_user_email_remove_users_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_price',
            field=models.IntegerField(default=0),
        ),
    ]
