# Generated by Django 5.2.5 on 2025-10-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_movies_movie_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='total_price',
        ),
    ]
